import menuIcon from './navMenu.svg'
import navArrow from './navArrow.svg'
import heartIcon from './navHeart.svg'
import userIcon from './navUser.svg'
import shoppingbag from './shoppingBag.svg'
import rightArrow from './right-arrow.svg'
import leftArrow from './left-arrow.svg'
import whiteShirt1 from './white-shirt1.png'
import blackShirt1 from './Black-shirt1.png'
import whiteShirt2 from './whiteShirt2.png'
import whiteShirt3 from './whiteShirt3.png'
import whiteShirt4 from './whiteShirt4.png'
import whiteShirt5 from './whiteShirt5.png'

export { menuIcon, navArrow, heartIcon, userIcon, shoppingbag, rightArrow, leftArrow, whiteShirt1, blackShirt1, whiteShirt2, whiteShirt3, whiteShirt4, whiteShirt5 }